import Head from "next/head";
import Link from "next/link";
import { Open_Sans, Raleway } from 'next/font/google'
import Testimonial from "~/components/Testimonial";

export const opensans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-opensans'
})

export const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${opensans.variable}` + " font-opensans flex min-h-screen flex-col items-center justify-center text-white bg-gradient-to-b from-[#2e026d] to-[#15162c]"}>
        All your files in one secure location, accessible anywhere.
        <Testimonial />
      </main>
    </>
  );
}
